### ISSUE TITLE
extra index.html in img folder

### ISSUE THREAD

**Issue by phoebeireland** [ANSHIKA1806/CardFlip_Game#2]
Why is there an extra index.html file in the img folder? It seems basically identical to the other index.html file.

**Comment by Sriram-bb63** [comment]
I would like to resolve this issue, please assign me

**Comment by phoebeireland** [comment]
I think you can just do it. Don't need to get permission as far as I know.

**Comment by Sriram-bb63** [comment]
Yes, but if you assign me I will use the PR in hactoberfest :)

**Comment by phoebeireland** [comment]
I'm not the maintainer of this repository sorry.

**Comment by Sriram-bb63** [comment]
You are the author of the repository...

**Comment by Sriram-bb63** [comment]
Oops my bad, I thought you are the owner of the repo

**Comment by Sriram-bb63** [comment]
Since the issue has been solved, please close it.
