### ISSUE TITLE
favicon is missing.

### ISSUE THREAD

**Issue by Aswal-Ashutosh** [ANSHIKA1806/CardFlip_Game#31]
- [x] index.html is containing **css** and **js** as well, which is making it harder to read and maintain code.
- [x] favicon is also missing.

**Comment by TechSpiritSS** [comment]
> * [x]  index.html is containing **css** and **js** as well., which is making it harder to read and maintain code.
I strongly agree to this one

**Comment by yas-sisodia** [comment]
@Aswal-Ashutosh ASSIGN THIS TASK TO ME, I CAN DO THIS

**Comment by Aswal-Ashutosh** [comment]
@ANSHIKA1806 someone has already separated CSS and JS. So only favicon is missing now. I have made PR #47  regarding this.
