### ISSUE TITLE
The pop and footer requerie modifiactions

### ISSUE THREAD

**Issue by mukulsinghal407** [ANSHIKA1806/CardFlip_Game#8]
The pop is way too down below on the page.
The addition of a favicon is also required.
Confetti drop on a match.
There is no responsive behavior on the page.

**Comment by Dcode-k** [comment]
@ANSHIKA1806 Please assign this issue to me.

**Comment by mukulsinghal407** [comment]
@Dcode-k well I stated this issue because I wanted to work on it. 
@ANSHIKA1806 Please assign me this task.

**Comment by ANSHIKA1806** [comment]
@mukulsinghal407 You can work on it.

**Comment by mukulsinghal407** [comment]
Thank you @ANSHIKA1806 for assigning this task to me.

**Comment by mukulsinghal407** [comment]
#27 @ANSHIKA1806 please refer to this pull request for the above mentioned issues and the defined resolution of the same.
