### ISSUE TITLE
README Whole Make-Over 

### ISSUE THREAD

**Issue by Pradumnasaraf** [ANSHIKA1806/CardFlip_Game#9]
**Changes/Addition**
- Proper Fonts
- Proper Language
- ScreenShots (Game)
- Logos for the programming language used
- Text Hyperlinks Addition

**Comment by Pradumnasaraf** [comment]
@ANSHIKA1806 Plz assign.
**It's almost completed a little glace of it**
![screenshot](https://user-images.githubusercontent.com/51878265/135979398-544f0828-a83d-48ec-a2eb-d95e4d3c0f08.png)

**Comment by ANSHIKA1806** [comment]
You can work on it.
